### PR TITLE
Fix map path + cosmetic change

### PR DESCRIPTION
**Pull request by johanvdw**
I noticed some issues while trying to get the project started (for the fosdem maps).

### CODE REVIEW

**Comment by codingcatgirl** [comment]
Yeah… no, you shouldn't try to get the project started right now. ^^ Everything has changed, nothing is like you know it from the last version and the docs do not reflect the current state at all. (This is btw also written in the Readme). I recommend waiting until after or near the 34c3 before getting started. Thanks!

**Comment by johanvdw** [comment]
FYI: the change was needed to run the 33c3 version.
Feel free to let me know when there is a newer version I could test/help on. There were some issues with the previous release which we must solve before a version for FOSDEM Is useful.
Eg https://github.com/FOSDEM/maps/issues/144

**Comment by codingcatgirl** [comment]
Ok, i supposed that, but as the docs will be deleted/rewritten soon, making commits now that refer to the old version doesn't make much sense, i think.

Thanks for your offer to help! The best way is basicalley to wait until c3nav gets online for the 34c3 and look for bugs before the congress starts :)

**Comment by ShinIce** [comment]
@codingcatgirl any ETA from your side to the release?

**Comment by codingcatgirl** [comment]
It will be stable on early december but there could still be changes up until the 34c3 (although everything will remain backwards compatible). Basic documentation might also only be ready by then.

**Pull request closed without merging**
