### PR TITLE
Add missing 35c3 mapping locations

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ Extracted from https://github.com/voc/35C3_schedule/blob/bbd04418794100930a996321137b3e1354fc24e3/everything.schedule.xml.

- [ ] Please add internal ids.

### CODE REVIEW

**Comment by codingcatgirl** [comment]
I added a few mappings in 72dfb21ba9eb3623cb28d7c65b3cd4885ac23b4d. Some assemblies are still missing, of course Assembly:CCL does not make sense… that would be the Blind Navigation Metting Point but i can't just put that in as Assembly:CCL

**Comment by codingcatgirl** [comment]
Just added the lounges and Blind Navigation Workshop (will show up in your next Schedule Update) was well

**Comment by codingcatgirl** [comment]
just added chaoszone

**Comment by johnjohndoe** [comment]
@codingcatgirl I added the latest changes [here](https://github.com/EventFahrplan/EventFahrplan/tree/c3nav) to be merged soon.

**Comment by codingcatgirl** [comment]
We just added the remaining ones. You might want to update it.

**Comment by johnjohndoe** [comment]
@codingcatgirl Thank you. Updated [here](https://github.com/EventFahrplan/EventFahrplan/tree/c3nav).

**Pull request merged**
