### PR TITLE
add map renderer

### PR DESCRIPTION
**Pull request by hwmrocker**

### CODE REVIEW

**Comment by hwmrocker** [comment]
it is allready merged outside of github

**Comment by nomoketo** [comment]
it is also already merged inside github…?

**Comment by hwmrocker** [comment]
seems so, https://github.com/c3nav/c3nav/blob/master/src/c3nav/mapdata/management/commands/createsvg.py

**Comment by hwmrocker** [comment]
seems so, https://github.com/c3nav/c3nav/blob/master/src/c3nav/mapdata/management/commands/createsvg.py

**Comment by nomoketo** [comment]
yeah, i know… so…? :D

**Pull request merged**
